language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: KlM15yi/6QpkoF4jntqhTqlYaaMYlvdz/YcRclPz/WjqiC7+lbb6TE5OvSLgB+lqzvp3f3qkP5yZjT+LLDXFX+prJ3mg/WS6AZ7+FJzSNeF+OrJ6O7J6U8qjgZcV6JCM3ySJQJQLCiBeZMNIEfVAjcCAram8bn/L62YOwwRVHIrkVo+ZviGIHO0oDjzwj0XnwXZeE7k2KvFvlblxd2AuWWG1Pqzb0RCdvkDGgS+uKZ+xSNNScfL5XQAS+QKdDZIm+wZ+SKcVedvqgjqFyyb6UoxKxPP9pNf3fahtfule6WNAtneCzyNkNHDnfwGEnp4teTyyr4p3F1YWaxlYE/eGfnHqvNw1xuwniDzSes/7kux0LvNdEiQ9xJmSe4+6J0KG0N94eZTFNtETRn3kxpySXE6uvZ3/NwLn8ncZ2i+5jxXLzWM4ZldI2tc40CWzU6LrGkDEhtEW9JeXonS4yxZsx81rEynV5/DKSuILqDjVAAwCBiPcsakycfYjBUJg2G8idKYzsPRY8uC05RCjHzSyuGo9a7aaH+xwkmsmEt+Qt9fWtWtOFFXdiXDT9DSWlW70LhYiIrgKHa8pWLF4Nw32RiSdpFweUFXRLrf0zhn+GmJjiXkb1d9vcxEgTGZfzJxytlErxkMxIB/v0xV9c25GIoSxN5OfsqsoU5rKLv86x3s=
  - secure: sdl9ZzlmeXokFqhBClXOPaFTEDMS4vVFoL7Fvka/fhCm0HaZEg3IPQZ7YBrGDkBj2Nyd4vjlgB/j0Nf5MYdP+OxKHgYRc8V13uJtIjTo0ZZNe0vHSPCKlVylJhwscXNU0o2YKEmJD2+FMVsvs/kpU+Ta3wiPy4tKqh+VvYng2bZw9WV1bxYug1u7tUyNVJUSBVhIGkfRKhD8BJg6EOqjHl9WGo8qhAqUC/U1mdBp98DmqoFw5pQyrgR/FEK7NiF84DZva6cjJXywG3Mll6rDQGjNQG6ZZT6hSdiaYqlZp7dYOGZMbmNm1WQthtIoj8Uv7xPTlGW+ZT9MYUJST9n0s0tt/07FTl4d8Bhy1vU8wdKQKbNzwYlpYNESbB5f9UhEZLSWD0OCwREg76aX337H1uk4MJCYqMNRKM/0Vi5MAgp42vq4ydX5O9y308cZNVigRApRzsjuAexMoFEPiWtVSGlIVqPmo/skbmq3Y2GVa1aRzZRVu/WGLKnsjzjo9kg1z+jVd75MGUGWTiM3VF8opsJWnm82tmHvJejWQEZk8ZwUNc+WQhZJJGua7LC/hvIY5Kq9MPKIdEe5kEZvR574axGhMAMyvB7qnWjNfqbd+KZltM4hIacSwDFsgS2OtlW9CmMAThZGYVsRDCmoAItGKDB2LOlWFHHuWDSvlxgrTSg=
