baseurl = "https://www.oddenmath.com/"
languageCode = "en-us"
title = "The Calculus Playlist"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "mathexpo"


[params]
    site_author = "Chris Odden"
    site_description = "A site devoted to teaching calculus."
    location = "Andover, Massachusetts"
    # Link custom assets relative to /static
    avatar = "img/cto_picture.jpg"
    header_background = "img/chalkboard.jpeg"
    header_title = "The Calculus Playlist"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
